language: python
python:
  - "2.7"
matrix:
  include:
  - env: INSTALL_VARIANT=pip
  - env: INSTALL_VARIANT=rpm
  - env: INSTALL_VARIANT=deb

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libx11-dev
      - libxtst-dev

# install any dependencies
install: "pip install -r packaging/pip_requirements.txt"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3  # give xvfb some time to start

# run tests
script:
  - python tests/test_calibrator.py
  - python tests/test_desktopcontrol.py
  - python tests/test_finder.py
  - python tests/test_path.py
  - python tests/test_region_calc.py
#  - python tests/test_region_control.py
#  - python tests/test_region_expect.py
  - python tests/test_target.py
# ultimately we want
#  - sh run_tests.sh

# use this to disable email notifications (e.g. while testing configuration)
#notifications:
#email: false
