language: python
python:
    - 3.4
    - 3.5
    - 3.6
    - pypy3
env:
    - INSTALL_VARIANT=pip DISABLE_OCR=1
matrix:
  include:
    - python: 3.6
      env: INSTALL_VARIANT=rpm
    - python: 3.6
      env: INSTALL_VARIANT=deb
  allow_failures:
    # the pypi setup is limited in terms of Qt4 and Tesseract dependencies
    - env: INSTALL_VARIANT=pip DISABLE_OCR=1

services:
  - docker
# docker images are not cached by travis due to vm recreation for each build
cache:
  - pip

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libx11-dev
      - libxtst-dev

# install any dependencies and build package
install:
  - if [[ $INSTALL_VARIANT == "pip" ]]; then travis_retry pip install -r packaging/pip_requirements.txt; fi

before_script:
  - export DISPLAY=:99.0
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1024x768x24"
  - sleep 3  # give xvfb some time to start
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' || $TRAVIS_PYTHON_VERSION == 'pypy3' ]]; then export DISABLE_AUTOPY=1; fi

# run tests
script:
  - if [[ $INSTALL_VARIANT != "pip" ]]; then cd packaging && bash packager_docker.sh; else cd tests && bash run_tests.sh; fi

# use this to disable email notifications (e.g. while testing configuration)
#notifications:
#email: false
